### ISSUE TITLE
[Inventory] Too many borders in 2D

### ISSUE THREAD

**Issue by avaer** [webaverse/app#138]
<img width="263" alt="Screen Shot 2020-10-14 at 9 56 07 AM" src="https://user-images.githubusercontent.com/6926057/96051858-616f8780-0e4a-11eb-929d-7d78a76e067b.png">

See the white outlines.

**Comment by ChrisEddy** [comment]
fixed

**Comment by avaer** [comment]
I think this is still an issue as of https://github.com/webaverse/app/pull/146.
