### ISSUE TITLE
App: METAANI VRMs not equippable

### ISSUE THREAD

**Issue by Vianvolaeus** [webaverse/app#1742]
METAANI VRM files are not equippable in-app currently. 

They have a similar rig to Meebits - notably, no finger bones, eye bones. 

![image](https://user-images.githubusercontent.com/80061436/140333297-b42fa35e-2462-48b0-a1f1-a707e77c7a3e.png)

Hierarchically, it appears that the first child of the root bones (hip bone) is not the next bone in humanoid chain - maybe this is interfering with the heuristic? 

![image](https://user-images.githubusercontent.com/80061436/140333495-ca44eb6a-c60f-43be-aad7-13a74092fe61.png)

Console shows following error on equip in-app:

![image](https://user-images.githubusercontent.com/80061436/140332915-5e58ebf9-be23-42ac-941e-676df349aa29.png)

I have checked the metadata in case of that being the issue and they appear to be sound on that front.

**Comment by Vianvolaeus** [comment]
Shoulder bones appear to not have any vertex influence (skinning) - not sure if that would be problematic

**Comment by skaljac** [comment]
How can I get example VRM for testing?

**Comment by avaer** [comment]
Should be fixed now?

**Comment by ahadshams** [comment]
not for me yet...

https://user-images.githubusercontent.com/44798013/140512455-13111801-0520-4f16-8a9f-84f0f956076e.mov

**Comment by skaljac** [comment]
https://github.com/webaverse/app/blob/4f9980a0167bc62eeaa1e4421912697b94300794/avatars/avatars.js#L2094

Fix is shown in avatar.js in main branch but app.webaverse.com still does not have that same code.

**Comment by avaer** [comment]
Yes, we have not deployed in a while. But I guess it's fixed locally.
