### ISSUE TITLE
Switching avatars from worlds is broken in master

### ISSUE THREAD

**Issue by alisaad673** [webaverse/app#3365]
Right now in master switching avatar works but the switched avatar acts weirdly with camera. Its as if the actual avatar and the apparent avatar are different

https://user-images.githubusercontent.com/35926530/180809907-5c441093-a087-46f1-b20a-b5e0726b557d.mp4

https://user-images.githubusercontent.com/35926530/180809981-6343dc2b-c83c-4e91-b193-ab692cc835ac.mp4

**Comment by lalalune** [comment]
fixed in master

**Comment by alisaad673** [comment]
This is still happening in master
Related: https://github.com/webaverse/app/issues/3297
