### ISSUE TITLE
APP: street entry point into parcels does not load the correct NFT

### ISSUE THREAD

**Issue by chrislatorres** [webaverse/app#678]
For example: instead of loading the parcel address and qs for NFT, it loads as

https://app.webaverse.com/?u=.%2Fparcels%2Fparcel.json&r=2-avaer-stacks-s1

**Comment by avaer** [comment]
Repro'd.

**Comment by avaer** [comment]
These parcels do not contain any content.

So we were defaulting to `parcel.json` as the content, and that was bugged.

**Comment by avaer** [comment]
We should warn folks that there is no content on the parcel so do not expect something to be there. It could make for a good placeholder package.

**Comment by avaer** [comment]
The loading should be fixed now; it is loading https://github.com/webaverse/parcels/blob/master/parcel.scn by default.

**Comment by chrislatorres** [comment]
Still not loading the NFT deployed to parcel, see 3 avaer stacks s1 -> https://app.webaverse.com/?u=https%3A%2F%2Fwebaverse.github.io%2Fparcels%2Fparcel.scn&r=3-avaer-stacks-s1

where the NFT deployed is 27

**Comment by avaer** [comment]
You're right, repro'd.

**Comment by avaer** [comment]
It should be loading now, though previews/holograms will not work until we have https://github.com/webaverse/app/issues/690
